export const lineButtons=[
    {
        name:"ALL",
        value:"all",
    },
    {
        name:"Top",
        value:"top",
    },
    {
        name:"Jungle",
        value:"jungle",
    },
    {
        name:"Mid",
        value:"mid",
    },
    {
        name:"Bottom",
        value:"bottom",
    },
    {
        name:"Support",
        value:"support",
    }
];

export const tierButtons=[
    {
        name:"Platinum",
        value:"plattinum",
    },
    {
        name:"Emerald",
        value:"emerald",
    },
    {
        name:"Diamond",
        value:"diamond",
    }
];